package me.rerere.material3

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import dynamiccolor.DynamicScheme

fun DynamicScheme.toColorScheme(): ColorScheme {
    val s = this
    return if (isDark) {
        darkColorScheme(
            primary = Color(s.primary),
            onPrimary = Color(s.onPrimary),
            primaryContainer = Color(s.primaryContainer),
            onPrimaryContainer = Color(s.onPrimaryContainer),
            inversePrimary = Color(s.inversePrimary),
            secondary = Color(s.secondary),
            onSecondary = Color(s.onSecondary),
            secondaryContainer = Color(s.secondaryContainer),
            onSecondaryContainer = Color(s.onSecondaryContainer),
            tertiary = Color(s.tertiary),
            onTertiary = Color(s.onTertiary),
            tertiaryContainer = Color(s.tertiaryContainer),
            onTertiaryContainer = Color(s.onTertiaryContainer),
            background = Color(s.background),
            onBackground = Color(s.onBackground),
            surface = Color(s.surface),
            onSurface = Color(s.onSurface),
            surfaceVariant = Color(s.surfaceVariant),
            onSurfaceVariant = Color(s.onSurfaceVariant),
            surfaceTint = Color(s.surfaceTint),
            inverseSurface = Color(s.inverseSurface),
            inverseOnSurface = Color(s.inverseOnSurface),
            error = if (s.isDark) Color(0xFFFFB4AB) else Color(0xFFBA1A1A),
            onError = if (s.isDark) Color(0xFF690005) else Color(0xFFFFFFFF),
            errorContainer = if (s.isDark) Color(0xFF93000A) else Color(0xFFFFDAD6),
            onErrorContainer = if (s.isDark) Color(0xFFFFDAD6) else Color(0xFF410002),
            outline = Color(s.outline),
            outlineVariant = Color(s.outlineVariant),
            scrim = Color(s.scrim),
            surfaceBright = Color(s.surfaceBright),
            surfaceDim = Color(s.surfaceDim),
            surfaceContainer = Color(s.surfaceContainer),
            surfaceContainerHigh = Color(s.surfaceContainerHigh),
            surfaceContainerHighest = Color(s.surfaceContainerHighest),
            surfaceContainerLow = Color(s.surfaceContainerLow),
            surfaceContainerLowest = Color(s.surfaceContainerLowest),
            primaryFixed = Color(s.primaryFixed),
            primaryFixedDim = Color(s.primaryFixedDim),
            onPrimaryFixed = Color(s.onPrimaryFixed),
            onPrimaryFixedVariant = Color(s.onPrimaryFixedVariant),
            secondaryFixed = Color(s.secondaryFixed),
            secondaryFixedDim = Color(s.secondaryFixedDim),
            onSecondaryFixed = Color(s.onSecondaryFixed),
            onSecondaryFixedVariant = Color(s.onSecondaryFixedVariant),
            tertiaryFixed = Color(s.tertiaryFixed),
            tertiaryFixedDim = Color(s.tertiaryFixedDim),
            onTertiaryFixed = Color(s.onTertiaryFixed),
            onTertiaryFixedVariant = Color(s.onTertiaryFixedVariant),
        )
    } else {
        lightColorScheme(
            primary = Color(s.primary),
            onPrimary = Color(s.onPrimary),
            primaryContainer = Color(s.primaryContainer),
            onPrimaryContainer = Color(s.onPrimaryContainer),
            inversePrimary = Color(s.inversePrimary),
            secondary = Color(s.secondary),
            onSecondary = Color(s.onSecondary),
            secondaryContainer = Color(s.secondaryContainer),
            onSecondaryContainer = Color(s.onSecondaryContainer),
            tertiary = Color(s.tertiary),
            onTertiary = Color(s.onTertiary),
            tertiaryContainer = Color(s.tertiaryContainer),
            onTertiaryContainer = Color(s.onTertiaryContainer),
            background = Color(s.background),
            onBackground = Color(s.onBackground),
            surface = Color(s.surface),
            onSurface = Color(s.onSurface),
            surfaceVariant = Color(s.surfaceVariant),
            onSurfaceVariant = Color(s.onSurfaceVariant),
            surfaceTint = Color(s.surfaceTint),
            inverseSurface = Color(s.inverseSurface),
            inverseOnSurface = Color(s.inverseOnSurface),
            error = if (s.isDark) Color(0xFFFFB4AB) else Color(0xFFBA1A1A),
            onError = if (s.isDark) Color(0xFF690005) else Color(0xFFFFFFFF),
            errorContainer = if (s.isDark) Color(0xFF93000A) else Color(0xFFFFDAD6),
            onErrorContainer = if (s.isDark) Color(0xFFFFDAD6) else Color(0xFF410002),
            outline = Color(s.outline),
            outlineVariant = Color(s.outlineVariant),
            scrim = Color(s.scrim),
            surfaceBright = Color(s.surfaceBright),
            surfaceDim = Color(s.surfaceDim),
            surfaceContainer = Color(s.surfaceContainer),
            surfaceContainerHigh = Color(s.surfaceContainerHigh),
            surfaceContainerHighest = Color(s.surfaceContainerHighest),
            surfaceContainerLow = Color(s.surfaceContainerLow),
            surfaceContainerLowest = Color(s.surfaceContainerLowest),
            primaryFixed = Color(s.primaryFixed),
            primaryFixedDim = Color(s.primaryFixedDim),
            onPrimaryFixed = Color(s.onPrimaryFixed),
            onPrimaryFixedVariant = Color(s.onPrimaryFixedVariant),
            secondaryFixed = Color(s.secondaryFixed),
            secondaryFixedDim = Color(s.secondaryFixedDim),
            onSecondaryFixed = Color(s.onSecondaryFixed),
            onSecondaryFixedVariant = Color(s.onSecondaryFixedVariant),
            tertiaryFixed = Color(s.tertiaryFixed),
            tertiaryFixedDim = Color(s.tertiaryFixedDim),
            onTertiaryFixed = Color(s.onTertiaryFixed),
            onTertiaryFixedVariant = Color(s.onTertiaryFixedVariant),
        )
    }
}
